In [2]:
import numpy as np
import cv2
from keras.models import Sequential
from keras.layers import Dense, Activation, Conv2D, Dropout, MaxPooling2D
from keras.models import Sequential
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.layers import Activation, Flatten, Dense, Dropout
from keras import *
from keras.layers.normalization import BatchNormalization

model = Sequential()
model.add(Conv2D(50,11,strides=(4,4),input_shape=(224,224,3)))
model.add(Conv2D(50,2))
model.add(Conv2D(50,2))
model.add(Conv2D(50,2))
model.add(Conv2D(50,2))
model.add(Conv2D(50,3))
model.add(Conv2D(50,2))
model.add(Conv2D(50,2))
model.add(Conv2D(50,2))
model.add(MaxPooling2D((5,5)))
model.add(Conv2D(50,2))
model.add(Conv2D(50,2))
model.add(Conv2D(50,2))
model.add(MaxPooling2D((3,3)))
model.add(Conv2D(50,2))

model.add(Flatten())

model.add(Dense(1000,activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(1000,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(2))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',optimizer=optimizers.RMSprop(lr=0.00001),metrics=['accuracy'])

model.load_weights("KerasApplication.model")


def GetImageFromFile(filename):
    img = cv2.imread("%s"%filename)
    return img

#Tabanca ve Bıçak için [1,0] matrisi
# çiçek için [0,1] matrisi kullanılmıştır.
InputData = np.array([])
InputData2 = np.array([])
InputData3 = np.array([])
InputData4 = np.array([])
InputData5 = np.array([])
InputData6 = np.array([])
InputData7 = np.array([])
InputData8 = np.array([])
InputData9 = np.array([])
InputData10 = np.array([])
InputData11 = np.array([])
InputData12 = np.array([])
InputData13 = np.array([])
InputData14 = np.array([])
InputData15 = np.array([])
InputData16 = np.array([])
InputData17 = np.array([])
InputData18 = np.array([])
InputData19 = np.array([])
InputData20 = np.array([])
InputData21 = np.array([])
InputData22 = np.array([])
InputData23 = np.array([])
InputData24 = np.array([])
InputData25 = np.array([])
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/TRAN1/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData = np.append(InputData,SizedImage)
    InputData = np.reshape(InputData,(-1,224,224,3)) 
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/TRAN2/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData7 = np.append(InputData7,SizedImage)
    InputData7 = np.reshape(InputData7,(-1,224,224,3)) 

for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/TRIS1/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData8 = np.append(InputData8,SizedImage)
    InputData8 = np.reshape(InputData8,(-1,224,224,3)) 

for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/TRIS2/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData9 = np.append(InputData9,SizedImage)
    InputData9 = np.reshape(InputData9,(-1,224,224,3)) 
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/UKLD1/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData2 = np.append(InputData2,SizedImage)
    InputData2 = np.reshape(InputData2,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/UKLD2/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData10 = np.append(InputData10,SizedImage)
    InputData10 = np.reshape(InputData10,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/UKPT1/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData11 = np.append(InputData11,SizedImage)
    InputData11 = np.reshape(InputData11,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/UKPT2/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData12 = np.append(InputData12,SizedImage)
    InputData12 = np.reshape(InputData12,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/ITRM1/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData3 = np.append(InputData3,SizedImage)
    InputData3 = np.reshape(InputData3,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/ITRM2/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData13 = np.append(InputData13,SizedImage)
    InputData13 = np.reshape(InputData13,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/ITNP1/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData14 = np.append(InputData14,SizedImage)
    InputData14 = np.reshape(InputData14,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/ITNP2/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData15 = np.append(InputData15,SizedImage)
    InputData15 = np.reshape(InputData15,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/ITNP3/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData16 = np.append(InputData16,SizedImage)
    InputData16 = np.reshape(InputData16,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/GRBE1/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData4 = np.append(InputData4,SizedImage)
    InputData4 = np.reshape(InputData4,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/GRBE2/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData17 = np.append(InputData17,SizedImage)
    InputData17 = np.reshape(InputData17,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/GRCG1/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData18 = np.append(InputData18,SizedImage)
    InputData18 = np.reshape(InputData18,(-1,224,224,3))

for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/GRCG2/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData19 = np.append(InputData19,SizedImage)
    InputData19 = np.reshape(InputData19,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/FRLY1/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData20 = np.append(InputData20,SizedImage)
    InputData20 = np.reshape(InputData20,(-1,224,224,3))

for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/FRLY2/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData21 = np.append(InputData21,SizedImage)
    InputData21 = np.reshape(InputData21,(-1,224,224,3))

for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/FRPR1/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData5 = np.append(InputData5,SizedImage)
    InputData5 = np.reshape(InputData5,(-1,224,224,3))

for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/FRPR2/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData22 = np.append(InputData22,SizedImage)
    InputData22 = np.reshape(InputData22,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/SPMD1/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData6 = np.append(InputData6,SizedImage)
    InputData6 = np.reshape(InputData6,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/SPMD2/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData23 = np.append(InputData23,SizedImage)
    InputData23 = np.reshape(InputData23,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/SPBC1/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData24 = np.append(InputData24,SizedImage)
    InputData24 = np.reshape(InputData24,(-1,224,224,3))
    
for i in range(2):
    receivedImage=0
    i=i+1
    string = 'IoTDevices/SPBC2/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    InputData25 = np.append(InputData25,SizedImage)
    InputData25 = np.reshape(InputData25,(-1,224,224,3))
    
    
Result = np.array
Result2 = np.array
Result3 = np.array
Result4 = np.array
Result5 = np.array
Result6 = np.array
Result7 = np.array
Result8 = np.array
Result9 = np.array
Result10 = np.array
Result11 = np.array
Result12 = np.array
Result13 = np.array
Result14 = np.array
Result15 = np.array
Result16 = np.array
Result17 = np.array
Result18 = np.array
Result19 = np.array
Result20 = np.array
Result21 = np.array
Result22 = np.array
Result23 = np.array
Result24 = np.array
Result25 = np.array
Result=(model.predict(InputData))
Result2=(model.predict(InputData2))
Result3=(model.predict(InputData3))
Result4=(model.predict(InputData4))
Result5=(model.predict(InputData5))
Result6=(model.predict(InputData6))
Result7=(model.predict(InputData7))
Result8=(model.predict(InputData8))
Result9=(model.predict(InputData9))
Result10=(model.predict(InputData10))
Result11=(model.predict(InputData11))
Result12=(model.predict(InputData12))
Result13=(model.predict(InputData13))
Result14=(model.predict(InputData14))
Result15=(model.predict(InputData15))
Result16=(model.predict(InputData16))
Result17=(model.predict(InputData17))
Result18=(model.predict(InputData18))
Result19=(model.predict(InputData19))
Result20=(model.predict(InputData20))
Result21=(model.predict(InputData21))
Result22=(model.predict(InputData22))
Result23=(model.predict(InputData23))
Result24=(model.predict(InputData24))
Result25=(model.predict(InputData25))
print(model.predict(InputData))
print(model.predict(InputData2))
print(model.predict(InputData3))
print(model.predict(InputData4))
print(model.predict(InputData5))
print(model.predict(InputData6))
print(model.predict(InputData7))
print(model.predict(InputData8))
print(model.predict(InputData9))
print(model.predict(InputData10))
print(model.predict(InputData11))
print(model.predict(InputData12))
print(model.predict(InputData13))
print(model.predict(InputData14))
print(model.predict(InputData15))
print(model.predict(InputData16))
print(model.predict(InputData17))
print(model.predict(InputData18))
print(model.predict(InputData19))
print(model.predict(InputData20))
print(model.predict(InputData21))
print(model.predict(InputData22))
print(model.predict(InputData23))
print(model.predict(InputData24))
print(model.predict(InputData25))
np.savetxt("IoTDevices/TRAN1.txt",np.array(Result), fmt="%s")
np.savetxt("IoTDevices/UKLD1.txt",np.array(Result2), fmt="%s")
np.savetxt("IoTDevices/ITRM1.txt",np.array(Result3), fmt="%s")
np.savetxt("IoTDevices/GRBE1.txt",np.array(Result4), fmt="%s")
np.savetxt("IoTDevices/FRPR1.txt",np.array(Result5), fmt="%s")
np.savetxt("IoTDevices/SPMD1.txt",np.array(Result6), fmt="%s")
np.savetxt("IoTDevices/TRAN2.txt",np.array(Result7), fmt="%s")
np.savetxt("IoTDevices/UKLD2.txt",np.array(Result10), fmt="%s")
np.savetxt("IoTDevices/ITRM2.txt",np.array(Result13), fmt="%s")
np.savetxt("IoTDevices/GRBE2.txt",np.array(Result17), fmt="%s")
np.savetxt("IoTDevices/FRPR2.txt",np.array(Result22), fmt="%s")
np.savetxt("IoTDevices/SPMD2.txt",np.array(Result23), fmt="%s")
np.savetxt("IoTDevices/TRIS1.txt",np.array(Result8), fmt="%s")
np.savetxt("IoTDevices/UKPT1.txt",np.array(Result11), fmt="%s")
np.savetxt("IoTDevices/ITNP1.txt",np.array(Result14), fmt="%s")
np.savetxt("IoTDevices/GRCG1.txt",np.array(Result18), fmt="%s")
np.savetxt("IoTDevices/FRLY1.txt",np.array(Result20), fmt="%s")
np.savetxt("IoTDevices/SPBC1.txt",np.array(Result24), fmt="%s")
np.savetxt("IoTDevices/TRIS2.txt",np.array(Result9), fmt="%s")
np.savetxt("IoTDevices/UKPT2.txt",np.array(Result12), fmt="%s")
np.savetxt("IoTDevices/ITNP2.txt",np.array(Result15), fmt="%s")
np.savetxt("IoTDevices/ITNP3.txt",np.array(Result16), fmt="%s")
np.savetxt("IoTDevices/GRCG2.txt",np.array(Result19), fmt="%s")
np.savetxt("IoTDevices/FRLY2.txt",np.array(Result22), fmt="%s")
np.savetxt("IoTDevices/SPBC2.txt",np.array(Result25), fmt="%s")

[[1. 0.]
 [1. 0.]]
[[1. 0.]
 [1. 0.]]
[[1. 0.]
 [1. 0.]]
[[1. 0.]
 [1. 0.]]
[[4.394681e-25 1.000000e+00]
 [1.000000e+00 0.000000e+00]]
[[0. 1.]
 [0. 1.]]
[[2.2733551e-11 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
[[1. 0.]
 [1. 0.]]
[[0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]]
[[1. 0.]
 [1. 0.]]
[[0. 1.]
 [1. 0.]]
[[1. 0.]
 [1. 0.]]
[[1. 0.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]]
[[1. 0.]
 [1. 0.]]
[[1. 0.]
 [1. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [1. 0.]]
[[1. 0.]
 [1. 0.]]
[[0. 1.]
 [0. 1.]]
[[0. 1.]
 [1. 0.]]
[[0. 1.]
 [1. 0.]]
[[1. 0.]
 [1. 0.]]
