In [1]:
import cv2
import numpy as np

def GetImageFromFile(filename):
    img = cv2.imread("%s"%filename)
    return img


InputData = np.array([])
for i in range(58):
    receivedImage=0
    i=i+1
    string = 'CNNImages/%s.jpg'%i
    receivedImage = GetImageFromFile(string)
    SizedImage = cv2.resize(receivedImage,(224,224))
    print(InputData)
    InputData = np.append(InputData,SizedImage)
    print (i+1)

    
InputData = np.reshape(InputData,(-1,224,224,3))
np.save("InputData",InputData)

print(InputData)
print(InputData.shape)

[]
2
[65. 63. 63. ... 61. 59. 59.]
3
[65. 63. 63. ...  7.  6.  8.]
4
[ 65.  63.  63. ... 181. 170. 173.]
5
[ 65.  63.  63. ... 203. 208. 207.]
6
[65. 63. 63. ... 22. 24. 25.]
7
[ 65.  63.  63. ... 217. 215. 215.]
8
[ 65.  63.  63. ...  68. 116. 164.]
9
[ 65.  63.  63. ... 237. 232. 229.]
10
[ 65.  63.  63. ... 255. 255. 255.]
11
[ 65.  63.  63. ... 209. 208. 194.]
12
[ 65.  63.  63. ... 255. 255. 255.]
13
[ 65.  63.  63. ...  94. 109. 118.]
14
[ 65.  63.  63. ... 255. 255. 255.]
15
[ 65.  63.  63. ... 245. 245. 245.]
16
[ 65.  63.  63. ... 255. 255. 255.]
17
[ 65.  63.  63. ... 255. 255. 255.]
18
[ 65.  63.  63. ... 255. 255. 255.]
19
[ 65.  63.  63. ... 255. 255. 255.]
20
[ 65.  63.  63. ... 255. 255. 255.]
21
[ 65.  63.  63. ... 255. 255. 255.]
22
[65. 63. 63. ... 50. 50. 50.]
23
[ 65.  63.  63. ... 255. 255. 255.]
24
[ 65.  63.  63. ... 255. 255. 255.]
25
[ 65.  63.  63. ... 255. 255. 255.]
26
[ 65.  63.  63. ... 255. 255. 255.]
27
[ 65.  63.  63. ... 255. 255. 255.]
28
[ 65.  63.  